Lobot
oQaris/QChess pull request #46
Opened 2021-08-03 11:57 UTC by Manjidomoe

Влад, посмотри плиз

2021-08-03 17:40 UTC, deeplaytrainer requested changes
1) ты не добавил в главный pom свой модуль, в связи с этим проект из ветки не собирается!
2) final ПОЖАЛУЙСТА!!!

2021-08-03 17:40 UTC, deeplaytrainer commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +    private final int MIN_INT = -9999;
чем MAX_INTEGER не устроил ?)

2021-08-03 17:40 UTC, deeplaytrainer commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +    public static int COUNT = 0;
ну private в таком случае. А то получается меняй кто хочет)

2021-08-03 17:40 UTC, deeplaytrainer commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +    private ChessMoveFunc<Integer> getAlgorithm(TraversalAlgorithm traversal) {
прикольно, мне нравится)

2021-08-03 17:40 UTC, deeplaytrainer commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +    private Move runRoot(ChessMoveFunc<Integer> algorithm) throws ChessError, ChessException {
если алгоритм является полем класса, зачем его здесь принимать ?

2021-08-03 17:40 UTC, deeplaytrainer commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +        setTurnIntoAll(moves);
не понял.

2021-08-03 17:40 UTC, deeplaytrainer commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +                if (!bestMoves.isEmpty()) {
лишнее на мой взгляд.

2021-08-03 17:40 UTC, deeplaytrainer commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +        if (moves.isEmpty() && egd.isCheck(curColor)) return color == curColor? MIN_INT : MAX_INT;
думаю проверкой на конец игры должен заниматься другой класс. Тут я так понял ты проверяешь пат, у вас нет такого метода в detector ? Тем более это не единственный вариант когда у нас конец игры.

2021-08-03 17:40 UTC, deeplaytrainer commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +            int cur = roomSettings.moveSystem.virtualMove(move, (from, to) ->
кар) вороны какие-то разлетались)

2021-08-03 17:40 UTC, deeplaytrainer commented on lobot/src/main/java/io/deeplay/qchess/lobot/strategy/EvaluateStrategy.java
> +public interface EvaluateStrategy {
вообще говоря не обязана функция возвращать int значения, вполне можно и даже более реалистично возвращать double.

2021-08-04 04:34 UTC, Manjidomoe commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +    private final int MIN_INT = -9999;
Тоже верно. Исправлю

2021-08-04 04:36 UTC, Manjidomoe commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +    public static int COUNT = 0;
эти переменные в тестах используются

2021-08-04 04:36 UTC, Manjidomoe commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +    private ChessMoveFunc<Integer> getAlgorithm(TraversalAlgorithm traversal) {
пасиба

2021-08-04 05:16 UTC, Manjidomoe commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +    private Move runRoot(ChessMoveFunc<Integer> algorithm) throws ChessError, ChessException {
Тоже верно. Исправлю

2021-08-04 05:20 UTC, Manjidomoe commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +        if (moves.isEmpty() && egd.isCheck(curColor)) return color == curColor? MIN_INT : MAX_INT;
egd это и есть EndGameDetector. Тут проверяется на мат (шах + нет ходов) это для терминального узла проверка. Проверка пата дальше; точнее даже не проверка, а просто в цикл входа не будет и вернётся значение для пата. Ничья на 75 ходов, 5-кратное повторение и недостаток материала проверяется в движке

2021-08-04 05:21 UTC, Manjidomoe commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +            int cur = roomSettings.moveSystem.virtualMove(move, (from, to) ->
Оке. Исправлю

2021-08-04 05:22 UTC, Manjidomoe commented on lobot/src/main/java/io/deeplay/qchess/lobot/strategy/EvaluateStrategy.java
> +public interface EvaluateStrategy {
все оценки под int подгоняются, в том числе матричная. Expectimax тоже округляет до нижнего целого. int меньше памяти занимает. Что прям принципиально на double менять?

2021-08-04 05:24 UTC, Manjidomoe commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +                if (!bestMoves.isEmpty()) {
Почему? Я не понимаю

2021-08-04 05:28 UTC, Manjidomoe commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +                if (!bestMoves.isEmpty()) {
А понял

2021-08-04 05:28 UTC, Manjidomoe commented on lobot/src/main/java/io/deeplay/qchess/lobot/LoBot.java
> +        setTurnIntoAll(moves);
Если ты про setTurnIntoAll - метод нужен чтобы всем ходам из списка имеющим статус "превращение пешки" задать фигуру в которую пешка будет превращена (для ботов в ферзя по-умолчанию)

2021-08-04 09:42 UTC, merged