Client Configuration
oQaris/QChess pull request #55
Opened 2021-08-10 10:12 UTC by Manjidomoe

Сервис для конфигурации, конфигурация для клиента, тесты

2021-08-10 10:16 UTC, Chae4ek reviewed
ИСПОЛЬЗУЙ MOCKITO

2021-08-10 10:17 UTC, oQaris approved these changes

2021-08-10 10:17 UTC, oQaris commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigException.java
> +    public ConfigException(ConfigExceptionEnum configExceptionEnum) {
final

2021-08-10 10:17 UTC, oQaris commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigExceptionEnum.java
> +    ABSENT_IP("Validate ip from config error (ip field is absent or ip is empty)"),
а чё не по русски?

2021-08-10 10:17 UTC, oQaris commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +    public static String validateIp(String property) throws ConfigException {
final
здесь и далее в файле

2021-08-10 10:17 UTC, oQaris commented on client/src/main/resources/client_configuration.conf
> +client.isTournament = false
пустую строку в конце каждого файла

2021-08-10 10:21 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigException.java
> +    public ConfigException(ConfigExceptionEnum configExceptionEnum) {
done

2021-08-10 10:22 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +    public static String validateIp(String property) throws ConfigException {
done

2021-08-10 10:25 UTC, Manjidomoe commented on client/src/main/resources/client_configuration.conf
> +client.isTournament = false
done

2021-08-10 12:25 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigExceptionEnum.java
> +    ABSENT_IP("Validate ip from config error (ip field is absent or ip is empty)"),
по казахкстански нада

2021-08-10 13:41 UTC, Chae4ek requested changes
В общем норм, НО:
1. Изучи Mockito. Кучу лишних файлов создавать не хорошо
2. Отформатируй форматтером код, где-то нехватает пробелов и отступов
3. Пустые строки в конце файлов
4. Переименнуй ClientConfig в ClientSettings. Я не знаю норм ли в ConfigService проводить валидацию, он же работает только с файлами, мб стоит вынести валидацию в ClientSettings

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigExceptionEnum.java
> +    ConfigExceptionEnum(final String message) {
где отступы

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigExceptionEnum.java
> +    ConfigExceptionEnum(final String message) {
вообще хз зачем мы везде private поле делали, его можно было public сделать

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigExceptionEnum.java
> +public enum ConfigExceptionEnum {
мы обычно везде писали ErrorCode вместо Enum

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +package io.deeplay.qchess.client.config;
вынеси в services/config/

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +        String[] octets = property.split("\\.");
bytes, зачем октеты, че выделываться, чтоб люди (я) гуглили что это

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.ABSENT_IP);
отформатируй

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
разрешите доебаца:
1. после "значения" ставится запятая
2. мне точки не нравятся ыыы
3. используй `<br>`, если надо перенести на другую строку. что за ;;;;
4. заумные слова еще какие-то, октеты ууу

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                    ConfigExceptionEnum.INCORRECT_IP_OCTET_VALUE);
отформатируй

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +        String[] octets = property.split("\\.");
или лучше ipBytesParts

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
`<br>`

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
`<br>`

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.ABSENT_BOOLEAN);
отформатируй

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
`<br>`

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
`{@link io.deeplay.qchess.client.view.gui.PlayerType}`

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.ABSENT_PLAYER_TYPE);
format plz

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
br

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.INCORRECT_PATH);
format

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.INCORRECT_PATH);
pattern сложный какой-то, добавь коммент, что он значит

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.ABSENT_COLOR);
format

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +        throw new ConfigException(ConfigExceptionEnum.INCORRECT_COLOR);
```suggestion
        return switch (property) {
            case "WHITE" -> Color.WHITE;
            case "BLACK" -> Color.BLACK;
            case "RANDOM" -> null;
            default -> throw new ConfigException(ConfigExceptionEnum.INCORRECT_COLOR);
        };
```

2021-08-10 13:41 UTC, Chae4ek commented on client/src/main/resources/client_configuration.conf
> +client.isTournament = false
че данон то, где пустая строка в этом файле?

2021-08-10 13:41 UTC, Chae4ek commented on client/src/test/java/io/deeplay/qchess/client/config/ClientConfigTest.java
> +        final String configPath = "/00_test_absent_ip.conf";
изучи Mockito

2021-08-10 13:41 UTC, Chae4ek commented on client/src/test/java/io/deeplay/qchess/client/config/ClientConfigTest.java
> +}
где пустая строка в конце

2021-08-10 13:43 UTC, Chae4ek commented on client/pom.xml
> +    </dependency>
`<!-- Tests -->`

2021-08-11 08:00 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ClientConfig.java
> +    private final String logBack;
один обозначает место где логи хранятся, второй путь до логбека.
Окей исправлю. А как javadoc для полей делается..

2021-08-11 09:30 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ClientConfig.java
> +    private final static String configPath = "/client_configuration.conf";
done

2021-08-11 09:31 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ClientConfig.java
> +    private final String logBack;
done

2021-08-11 09:31 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.ABSENT_COLOR);
не понял

2021-08-11 09:32 UTC, Manjidomoe commented on client/pom.xml
> +    </dependency>
done

2021-08-11 09:34 UTC, Manjidomoe commented on client/src/test/java/io/deeplay/qchess/client/config/ClientConfigTest.java
> +}
done

2021-08-11 09:35 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +        throw new ConfigException(ConfigExceptionEnum.INCORRECT_COLOR);
done

2021-08-11 09:36 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ClientConfig.java
> +            fis = new FileInputStream(Objects.requireNonNull(getClass().getResource(configPath)).getFile());
done

2021-08-11 09:38 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ClientConfig.java
> +package io.deeplay.qchess.client.config;
done

2021-08-11 09:38 UTC, Manjidomoe commented on client/src/main/resources/client_configuration.conf
> +client.isTournament = false
done

2021-08-11 10:16 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ClientConfig.java
> +    private final boolean isTournament;
вот в чем вопрос...

2021-08-11 10:21 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigException.java
> +    }
но если сильно надо поле и метод, можно оставить, но super() все равно нужен

2021-08-11 11:00 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ClientConfig.java
> +     * WHITE или BLACK. null - если в конфигах было RANDOM
вроде отформатировалось

2021-08-11 11:04 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigException.java
> +    }
для тестов нужно

2021-08-11 11:07 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +package io.deeplay.qchess.client.config;
сделано

2021-08-11 11:08 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigExceptionEnum.java
> +public enum ConfigExceptionEnum {
оке, исправлю

2021-08-11 11:09 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigExceptionEnum.java
> +public enum ConfigExceptionEnum {
done

2021-08-11 11:21 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +        String[] octets = property.split("\\.");
шо первое в голову пришло то и написал. Нужно Серёгино экспертное мнение.

2021-08-11 11:24 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
1. и правда доэбався
2. я с ваших jvdc пример брал, сами там точки ставите.
3. ";" после элемента списка ставят, норм оформление чи нет,
4. единственное "заумное" слово - октет

2021-08-11 11:24 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
уже отвечал

2021-08-11 11:24 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
уже отвечал

2021-08-11 11:25 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
уже отвечал

2021-08-11 11:30 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.INCORRECT_PATH);
done

2021-08-11 11:35 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +     */
done

2021-08-11 11:35 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.ABSENT_BOOLEAN);
done

2021-08-11 11:35 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                    ConfigExceptionEnum.INCORRECT_IP_OCTET_VALUE);
done

2021-08-11 11:36 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.ABSENT_IP);
done

2021-08-11 11:36 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/config/ConfigService.java
> +                ConfigExceptionEnum.ABSENT_PLAYER_TYPE);
done

2021-08-11 16:14 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/service/config/ConfigService.java
> +        final String pattern = "/([\\w\\s]+/)*";
А если нужен относительный путь, например:
```
./path/
../path/
../../path/
../../path/../path2/
./
```
Либо такой экзотический (который в принципе можно и не учитывать):
`./././`

2021-08-11 16:30 UTC, Chae4ek commented on client/src/test/resources/53_test_complete.conf
> +client.logBack = /arara 4343 _ _9/
И вот как мне сходу понять, верно ли это или нет? Я бы хотел видеть это рядом с тестом...

2021-08-12 04:11 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/service/config/ConfigService.java
> +        final String pattern = "/([\\w\\s]+/)*";
а точно, точки ещё

2021-08-12 04:12 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/service/config/ConfigService.java
> +        }
1. Октеты максимально точно всё отражают
2. упс

2021-08-12 04:45 UTC, Manjidomoe commented on client/src/test/resources/53_test_complete.conf
> +client.logBack = /arara 4343 _ _9/
оке....

2021-08-12 04:49 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/service/config/ConfigService.java
> +        }
done

2021-08-12 05:06 UTC, Manjidomoe commented on client/src/test/resources/53_test_complete.conf
> +client.logBack = /arara 4343 _ _9/
done

2021-08-12 05:53 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/service/config/ConfigService.java
> +        final String pattern = "/([\\w\\s]+/)*";
done

2021-08-12 06:15 UTC, Chae4ek approved these changes
жаль не отформатировал, ну да ладно

2021-08-12 06:15 UTC, Chae4ek commented on client/src/test/resources/53_test_complete.conf
> +client.logBack = /kkcd d _ dfd 1/
а в чем смысл заменять было?

2021-08-12 06:20 UTC, merged