возможность в GUI выбрать цвет за который будешь играть
oQaris/QChess pull request #57
Opened 2021-08-11 10:13 UTC by Manjidomoe

Рефакторинг и чистку этого кала я себе уже вынес в отдельную задачу. Не в контексте этой задачи чистка будет делаться. Так что про это комментарии не надо.
Лёша, нужно реализовать метод из ClienController выбора цвета.

2021-08-11 10:35 UTC, Chae4ek requested changes
View не должна ничего знать об игре. Это нарушит принцип MVC. Создай ViewColor вместо Color из game

2021-08-11 10:35 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/controller/ClientController.java
> +    }
уххх костыли. почему у View все еще нет своего Color ?

2021-08-11 10:35 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/ChooseMyColorFrame.java
> +import io.deeplay.qchess.game.model.Color;
View не должна знать об игре

2021-08-11 10:35 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/ChooseMyColorFrame.java
> +        addRadioButton("Любым", false, null);
ахахах
-- какой? - белый.
-- кого? - черных.
-- каким? - любым.

2021-08-11 10:35 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/MainFrame.java
> +import io.deeplay.qchess.game.model.Color;
сделай отдельный цвет для View

2021-08-11 11:40 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/gui/ChooseMyColorFrame.java
> +        addRadioButton("Любым", false, null);
(

2021-08-11 11:41 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/gui/ChooseMyColorFrame.java
> +        addRadioButton("Любым", false, null);
done

2021-08-11 11:45 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/controller/ClientController.java
> +    }
done

2021-08-11 11:45 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/gui/ChooseMyColorFrame.java
> +import io.deeplay.qchess.game.model.Color;
done

2021-08-11 11:46 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/gui/MainFrame.java
> +import io.deeplay.qchess.game.model.Color;
done

2021-08-11 11:51 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/controller/ClientController.java
> +    }
а null на нормальный тип в перечислении заменить?

2021-08-11 12:04 UTC, Chae4ek approved these changes

2021-08-12 04:09 UTC, oQaris approved these changes

2021-08-12 04:09 UTC, merged