Подсчёт рейтинга Эло для игроков
oQaris/QChess pull request #63
Opened 2021-08-13 15:36 UTC by oQaris

2021-08-14 13:22 UTC, Chae4ek requested changes
1. pullELO() работает не правильно, написал подробно в комментариях почему
2. new Gson() можно заменить на static final поле, чтобы не создавать его каждый раз

2021-08-14 13:22 UTC, Chae4ek commented on core/src/main/java/io/deeplay/qchess/core/RatingELO.java
> +            elo = new Gson().fromJson(reader, new TypeToken<Map<String, Long>>() {}.getType());
Правильнее будет так:
`elo = new Gson().fromJson(reader, new TypeToken<ConcurrentHashMap<String, Long>>() {}.getType());`
либо с использованием ConcurrentMap, но лучше явно указать, чтоб не гадать что там по стандарту подставляется
На текущем твоем коде не пройдет следующий тест (в обеих проверках):
```
elo = new Gson().fromJson(reader, new TypeToken<Map<String, Long>>() {}.getType());
if (elo.getClass() != ConcurrentHashMap.class) {
    Assert.fail();
}
if (!(elo instanceof ConcurrentMap)) {
    Assert.fail();
}
```
Создавать TypeToken хорошее решение, т.к. без него по стандарту все числа считаются как double, из-за чего становится невозможным сравнивать числа с long, даже если мапа содержит Long, как в этом тесте:
```
String json = "{\"test\":123}";
Map<String, Long> elo = new Gson().<Map<String, Long>>fromJson(json, Map.class);
if (elo.get("test") != 123L) { // ClassCastException error
    // Assert.fail();
}
```

2021-08-14 16:36 UTC, oQaris commented on core/src/main/java/io/deeplay/qchess/core/ArenaStats.java
> +        logger.info("-=+=+=+=+=+=+=+=- Second -=+=+=+=+=+=+=+=-");
Спасибо, я старался

2021-08-14 16:37 UTC, oQaris commented on core/src/main/java/io/deeplay/qchess/core/Arena.java
> +                            : 0.5);
ну шо поделать. тут и Solarlint жалуется. Максимум могу на ифы разбить

2021-08-14 16:39 UTC, oQaris commented on core/src/main/java/io/deeplay/qchess/core/RatingELO.java
> +            elo = new Gson().fromJson(reader, new TypeToken<Map<String, Long>>() {}.getType());
понял

2021-08-14 16:40 UTC, oQaris commented on core/src/main/java/io/deeplay/qchess/core/RatingELO.java
> +            new Gson().toJson(elo, writer);
не статиком, а просто полем. статик - зло. он используется только в Arena, где действительно необходим. а в Elo и Stats пусть лучше его не будет

2021-08-15 05:55 UTC, oQaris commented on game/src/main/java/io/deeplay/qchess/game/player/AttackBot.java
> -            final Figure figure = board.getFigureUgly(move.getFrom());
Кто это сделал, признавайтесь? у меня атакующий бот всегда ладьёй ходил из за этого

2021-08-15 05:55 UTC, oQaris commented on core/src/main/java/io/deeplay/qchess/core/RatingELO.java
> +        Files.move(
Если кому не понятно, это чтоб случайно не потерять файл с рейтингом. Запись идёт во временный файл, а потом происходит атомарная замена

2021-08-15 09:56 UTC, Chae4ek approved these changes

2021-08-16 05:07 UTC, Manjidomoe commented on core/src/main/java/io/deeplay/qchess/core/RatingELO.java
> +    private long calculateElo(final long rA, final long rB, final float sA) {
а шо нормальные имена нельзя сделать, чтобы лишние жаба доки не расписывать

2021-08-16 05:07 UTC, Manjidomoe commented on core/src/main/java/io/deeplay/qchess/core/RatingELO.java
> +        assert sA >= 0 && sA <= 1;
assert такое себе

2021-08-16 05:07 UTC, Manjidomoe commented on game/src/main/java/io/deeplay/qchess/game/player/AttackBot.java
> +            final int curGrade = attackedFigure == null ? 0 : grades.get(attackedFigure.figureType);
буду как Влад душить за cur

2021-08-16 05:20 UTC, oQaris commented on game/src/main/java/io/deeplay/qchess/game/player/AttackBot.java
> +            final int curGrade = attackedFigure == null ? 0 : grades.get(attackedFigure.figureType);
это корпоративное сокращение

2021-08-16 05:20 UTC, oQaris commented on core/src/main/java/io/deeplay/qchess/core/RatingELO.java
> +        assert sA >= 0 && sA <= 1;
заменил на if

2021-08-16 05:22 UTC, oQaris commented on core/src/main/java/io/deeplay/qchess/core/RatingELO.java
> +    private long calculateElo(final long rA, final long rB, final float sA) {
ладно

2021-08-16 05:23 UTC, oQaris commented on core/src/main/java/io/deeplay/qchess/core/Arena.java
> +            final float firstPlayerFactor = getFactor(firstPlayer.getColor(), gameResult);
фактор может быть только 1, 0 и 0.5, думаю наглядней флоат

2021-08-16 06:08 UTC, Manjidomoe approved these changes

2021-08-16 06:08 UTC, merged