Gui fix
oQaris/QChess pull request #68
Opened 2021-08-16 12:05 UTC by Manjidomoe

2021-08-17 09:50 UTC, Chae4ek requested changes

2021-08-17 09:50 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/CloseFrameListener.java
> +                        null);
что за null, обясни

2021-08-17 09:50 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/MainFrame.java
> +        //startButton.setFocusPainted(false);
удоли

2021-08-17 09:50 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +                                }
final

2021-08-17 09:50 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +            for(ViewFigureType viewFigureType : ViewFigureType.values()) {
final

2021-08-17 09:50 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +        for(ViewFigure viewFigure : figureArtMap.keySet()) {
final

2021-08-17 09:50 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +                // logger + what do i can do?
удоли или логируй нормально

2021-08-17 09:50 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/model/ViewFigure.java
> +    public boolean equals(Object o) {
final

2021-08-17 09:50 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/model/ViewFigure.java
> +        ViewFigure that = (ViewFigure) o;
final

2021-08-18 05:58 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/gui/CloseFrameListener.java
> +                        null);
в этот параметр передаётся элемент на который будет падать фокус при спавне окна. Null в этом месте, значит фокуса не будет нигде

2021-08-18 05:59 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/gui/MainFrame.java
> +        //startButton.setFocusPainted(false);
done

2021-08-18 06:00 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +                                }
done

2021-08-18 06:00 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +            for(ViewFigureType viewFigureType : ViewFigureType.values()) {
done

2021-08-18 06:01 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +        for(ViewFigure viewFigure : figureArtMap.keySet()) {
done

2021-08-18 06:02 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +                // logger + what do i can do?
done

2021-08-18 06:02 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/model/ViewFigure.java
> +    public boolean equals(Object o) {
done

2021-08-18 06:02 UTC, Manjidomoe commented on client/src/main/java/io/deeplay/qchess/client/view/model/ViewFigure.java
> +        ViewFigure that = (ViewFigure) o;
done

2021-08-18 08:00 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +            } catch (final IOException | NullPointerException | IllegalArgumentException e) { }
че за пробел { }

2021-08-18 08:01 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +            } catch (final IOException | NullPointerException | IllegalArgumentException e) { }
{
}

2021-08-18 08:01 UTC, Chae4ek commented on client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
> +            } catch (final IOException | NullPointerException | IllegalArgumentException e) { }
e замени на ignore

2021-08-18 08:01 UTC, Chae4ek approved these changes

2021-08-18 13:42 UTC, Chae4ek approved these changes

2021-08-18 13:44 UTC, oQaris approved these changes
Если исправил замечания Льоши, то норм, вливай

2021-08-18 18:24 UTC, merged